// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: internal/proto/upload.proto

package uploadpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UploadRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// first message should contain metadata
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadRequest_Info
	//	*UploadRequest_Chunk
	Payload       isUploadRequest_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_internal_proto_upload_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_upload_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_upload_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetPayload() isUploadRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadRequest) GetInfo() *FileInfo {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *UploadRequest) GetChunk() *FileChunk {
	if x != nil {
		if x, ok := x.Payload.(*UploadRequest_Chunk); ok {
			return x.Chunk
		}
	}
	return nil
}

type isUploadRequest_Payload interface {
	isUploadRequest_Payload()
}

type UploadRequest_Info struct {
	Info *FileInfo `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type UploadRequest_Chunk struct {
	Chunk *FileChunk `protobuf:"bytes,2,opt,name=chunk,proto3,oneof"`
}

func (*UploadRequest_Info) isUploadRequest_Payload() {}

func (*UploadRequest_Chunk) isUploadRequest_Payload() {}

type FileInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`                              // e.g. "streamhub"
	ObjectName    string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`    // path inside bucket, e.g. "videos/movie.mp4"
	ContentType   string                 `protobuf:"bytes,3,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"` // "video/mp4"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileInfo) Reset() {
	*x = FileInfo{}
	mi := &file_internal_proto_upload_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileInfo) ProtoMessage() {}

func (x *FileInfo) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_upload_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileInfo.ProtoReflect.Descriptor instead.
func (*FileInfo) Descriptor() ([]byte, []int) {
	return file_internal_proto_upload_proto_rawDescGZIP(), []int{1}
}

func (x *FileInfo) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *FileInfo) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *FileInfo) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

type FileChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FileChunk) Reset() {
	*x = FileChunk{}
	mi := &file_internal_proto_upload_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FileChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FileChunk) ProtoMessage() {}

func (x *FileChunk) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_upload_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FileChunk.ProtoReflect.Descriptor instead.
func (*FileChunk) Descriptor() ([]byte, []int) {
	return file_internal_proto_upload_proto_rawDescGZIP(), []int{2}
}

func (x *FileChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	ObjectName    string                 `protobuf:"bytes,3,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_internal_proto_upload_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_upload_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_upload_proto_rawDescGZIP(), []int{3}
}

func (x *UploadResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *UploadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UploadResponse) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

type GetSignedUrlRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bucket        string                 `protobuf:"bytes,1,opt,name=bucket,proto3" json:"bucket,omitempty"`
	ObjectName    string                 `protobuf:"bytes,2,opt,name=object_name,json=objectName,proto3" json:"object_name,omitempty"`
	ExpirySeconds int32                  `protobuf:"varint,3,opt,name=expiry_seconds,json=expirySeconds,proto3" json:"expiry_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignedUrlRequest) Reset() {
	*x = GetSignedUrlRequest{}
	mi := &file_internal_proto_upload_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedUrlRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedUrlRequest) ProtoMessage() {}

func (x *GetSignedUrlRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_upload_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedUrlRequest.ProtoReflect.Descriptor instead.
func (*GetSignedUrlRequest) Descriptor() ([]byte, []int) {
	return file_internal_proto_upload_proto_rawDescGZIP(), []int{4}
}

func (x *GetSignedUrlRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *GetSignedUrlRequest) GetObjectName() string {
	if x != nil {
		return x.ObjectName
	}
	return ""
}

func (x *GetSignedUrlRequest) GetExpirySeconds() int32 {
	if x != nil {
		return x.ExpirySeconds
	}
	return 0
}

type GetSignedUrlResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSignedUrlResponse) Reset() {
	*x = GetSignedUrlResponse{}
	mi := &file_internal_proto_upload_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSignedUrlResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSignedUrlResponse) ProtoMessage() {}

func (x *GetSignedUrlResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_upload_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSignedUrlResponse.ProtoReflect.Descriptor instead.
func (*GetSignedUrlResponse) Descriptor() ([]byte, []int) {
	return file_internal_proto_upload_proto_rawDescGZIP(), []int{5}
}

func (x *GetSignedUrlResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_internal_proto_upload_proto protoreflect.FileDescriptor

const file_internal_proto_upload_proto_rawDesc = "" +
	"\n" +
	"\x1binternal/proto/upload.proto\x12\x06upload\"m\n" +
	"\rUploadRequest\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x10.upload.FileInfoH\x00R\x04info\x12)\n" +
	"\x05chunk\x18\x02 \x01(\v2\x11.upload.FileChunkH\x00R\x05chunkB\t\n" +
	"\apayload\"f\n" +
	"\bFileInfo\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName\x12!\n" +
	"\fcontent_type\x18\x03 \x01(\tR\vcontentType\"\x1f\n" +
	"\tFileChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"[\n" +
	"\x0eUploadResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1f\n" +
	"\vobject_name\x18\x03 \x01(\tR\n" +
	"objectName\"u\n" +
	"\x13GetSignedUrlRequest\x12\x16\n" +
	"\x06bucket\x18\x01 \x01(\tR\x06bucket\x12\x1f\n" +
	"\vobject_name\x18\x02 \x01(\tR\n" +
	"objectName\x12%\n" +
	"\x0eexpiry_seconds\x18\x03 \x01(\x05R\rexpirySeconds\"(\n" +
	"\x14GetSignedUrlResponse\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url2\x95\x01\n" +
	"\rUploadService\x129\n" +
	"\x06Upload\x12\x15.upload.UploadRequest\x1a\x16.upload.UploadResponse(\x01\x12I\n" +
	"\fGetSignedUrl\x12\x1b.upload.GetSignedUrlRequest\x1a\x1c.upload.GetSignedUrlResponseB\x1bZ\x19./internal/proto;uploadpbb\x06proto3"

var (
	file_internal_proto_upload_proto_rawDescOnce sync.Once
	file_internal_proto_upload_proto_rawDescData []byte
)

func file_internal_proto_upload_proto_rawDescGZIP() []byte {
	file_internal_proto_upload_proto_rawDescOnce.Do(func() {
		file_internal_proto_upload_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_upload_proto_rawDesc), len(file_internal_proto_upload_proto_rawDesc)))
	})
	return file_internal_proto_upload_proto_rawDescData
}

var file_internal_proto_upload_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_internal_proto_upload_proto_goTypes = []any{
	(*UploadRequest)(nil),        // 0: upload.UploadRequest
	(*FileInfo)(nil),             // 1: upload.FileInfo
	(*FileChunk)(nil),            // 2: upload.FileChunk
	(*UploadResponse)(nil),       // 3: upload.UploadResponse
	(*GetSignedUrlRequest)(nil),  // 4: upload.GetSignedUrlRequest
	(*GetSignedUrlResponse)(nil), // 5: upload.GetSignedUrlResponse
}
var file_internal_proto_upload_proto_depIdxs = []int32{
	1, // 0: upload.UploadRequest.info:type_name -> upload.FileInfo
	2, // 1: upload.UploadRequest.chunk:type_name -> upload.FileChunk
	0, // 2: upload.UploadService.Upload:input_type -> upload.UploadRequest
	4, // 3: upload.UploadService.GetSignedUrl:input_type -> upload.GetSignedUrlRequest
	3, // 4: upload.UploadService.Upload:output_type -> upload.UploadResponse
	5, // 5: upload.UploadService.GetSignedUrl:output_type -> upload.GetSignedUrlResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_proto_upload_proto_init() }
func file_internal_proto_upload_proto_init() {
	if File_internal_proto_upload_proto != nil {
		return
	}
	file_internal_proto_upload_proto_msgTypes[0].OneofWrappers = []any{
		(*UploadRequest_Info)(nil),
		(*UploadRequest_Chunk)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_upload_proto_rawDesc), len(file_internal_proto_upload_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_proto_upload_proto_goTypes,
		DependencyIndexes: file_internal_proto_upload_proto_depIdxs,
		MessageInfos:      file_internal_proto_upload_proto_msgTypes,
	}.Build()
	File_internal_proto_upload_proto = out.File
	file_internal_proto_upload_proto_goTypes = nil
	file_internal_proto_upload_proto_depIdxs = nil
}
