// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.1
// source: api/proto/v1/chat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BroadcastRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ConversationId string                 `protobuf:"bytes,2,opt,name=conversation_id,json=conversationId,proto3" json:"conversation_id,omitempty"`
	SenderId       string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Content        string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	MessageType    string                 `protobuf:"bytes,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"`
	RecipientIds   []string               `protobuf:"bytes,6,rep,name=recipient_ids,json=recipientIds,proto3" json:"recipient_ids,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastRequest) Reset() {
	*x = BroadcastRequest{}
	mi := &file_api_proto_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastRequest) ProtoMessage() {}

func (x *BroadcastRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastRequest.ProtoReflect.Descriptor instead.
func (*BroadcastRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *BroadcastRequest) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *BroadcastRequest) GetConversationId() string {
	if x != nil {
		return x.ConversationId
	}
	return ""
}

func (x *BroadcastRequest) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *BroadcastRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *BroadcastRequest) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

func (x *BroadcastRequest) GetRecipientIds() []string {
	if x != nil {
		return x.RecipientIds
	}
	return nil
}

func (x *BroadcastRequest) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type BroadcastResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DeliveredCount int32                  `protobuf:"varint,2,opt,name=delivered_count,json=deliveredCount,proto3" json:"delivered_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BroadcastResponse) Reset() {
	*x = BroadcastResponse{}
	mi := &file_api_proto_v1_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BroadcastResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BroadcastResponse) ProtoMessage() {}

func (x *BroadcastResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BroadcastResponse.ProtoReflect.Descriptor instead.
func (*BroadcastResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_chat_proto_rawDescGZIP(), []int{1}
}

func (x *BroadcastResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *BroadcastResponse) GetDeliveredCount() int32 {
	if x != nil {
		return x.DeliveredCount
	}
	return 0
}

type OnlineUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUsersRequest) Reset() {
	*x = OnlineUsersRequest{}
	mi := &file_api_proto_v1_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUsersRequest) ProtoMessage() {}

func (x *OnlineUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUsersRequest.ProtoReflect.Descriptor instead.
func (*OnlineUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_chat_proto_rawDescGZIP(), []int{2}
}

func (x *OnlineUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type OnlineUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OnlineUserIds []string               `protobuf:"bytes,1,rep,name=online_user_ids,json=onlineUserIds,proto3" json:"online_user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnlineUsersResponse) Reset() {
	*x = OnlineUsersResponse{}
	mi := &file_api_proto_v1_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnlineUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnlineUsersResponse) ProtoMessage() {}

func (x *OnlineUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnlineUsersResponse.ProtoReflect.Descriptor instead.
func (*OnlineUsersResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_chat_proto_rawDescGZIP(), []int{3}
}

func (x *OnlineUsersResponse) GetOnlineUserIds() []string {
	if x != nil {
		return x.OnlineUserIds
	}
	return nil
}

type PresenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // "online" or "offline"
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceRequest) Reset() {
	*x = PresenceRequest{}
	mi := &file_api_proto_v1_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceRequest) ProtoMessage() {}

func (x *PresenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceRequest.ProtoReflect.Descriptor instead.
func (*PresenceRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_chat_proto_rawDescGZIP(), []int{4}
}

func (x *PresenceRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PresenceRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PresenceRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type PresenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PresenceResponse) Reset() {
	*x = PresenceResponse{}
	mi := &file_api_proto_v1_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PresenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PresenceResponse) ProtoMessage() {}

func (x *PresenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_v1_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PresenceResponse.ProtoReflect.Descriptor instead.
func (*PresenceResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_v1_chat_proto_rawDescGZIP(), []int{5}
}

func (x *PresenceResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_api_proto_v1_chat_proto protoreflect.FileDescriptor

const file_api_proto_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x17api/proto/v1/chat.proto\x12\achat.v1\"\xf8\x01\n" +
	"\x10BroadcastRequest\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fconversation_id\x18\x02 \x01(\tR\x0econversationId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\tR\vmessageType\x12#\n" +
	"\rrecipient_ids\x18\x06 \x03(\tR\frecipientIds\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"V\n" +
	"\x11BroadcastResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fdelivered_count\x18\x02 \x01(\x05R\x0edeliveredCount\"/\n" +
	"\x12OnlineUsersRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"=\n" +
	"\x13OnlineUsersResponse\x12&\n" +
	"\x0fonline_user_ids\x18\x01 \x03(\tR\ronlineUserIds\"`\n" +
	"\x0fPresenceRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\",\n" +
	"\x10PresenceResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xec\x01\n" +
	"\vChatService\x12I\n" +
	"\x10BroadcastMessage\x12\x19.chat.v1.BroadcastRequest\x1a\x1a.chat.v1.BroadcastResponse\x12K\n" +
	"\x0eGetOnlineUsers\x12\x1b.chat.v1.OnlineUsersRequest\x1a\x1c.chat.v1.OnlineUsersResponse\x12E\n" +
	"\x0eNotifyPresence\x12\x18.chat.v1.PresenceRequest\x1a\x19.chat.v1.PresenceResponseB\n" +
	"Z\b./pkg/pbb\x06proto3"

var (
	file_api_proto_v1_chat_proto_rawDescOnce sync.Once
	file_api_proto_v1_chat_proto_rawDescData []byte
)

func file_api_proto_v1_chat_proto_rawDescGZIP() []byte {
	file_api_proto_v1_chat_proto_rawDescOnce.Do(func() {
		file_api_proto_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_v1_chat_proto_rawDesc), len(file_api_proto_v1_chat_proto_rawDesc)))
	})
	return file_api_proto_v1_chat_proto_rawDescData
}

var file_api_proto_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_proto_v1_chat_proto_goTypes = []any{
	(*BroadcastRequest)(nil),    // 0: chat.v1.BroadcastRequest
	(*BroadcastResponse)(nil),   // 1: chat.v1.BroadcastResponse
	(*OnlineUsersRequest)(nil),  // 2: chat.v1.OnlineUsersRequest
	(*OnlineUsersResponse)(nil), // 3: chat.v1.OnlineUsersResponse
	(*PresenceRequest)(nil),     // 4: chat.v1.PresenceRequest
	(*PresenceResponse)(nil),    // 5: chat.v1.PresenceResponse
}
var file_api_proto_v1_chat_proto_depIdxs = []int32{
	0, // 0: chat.v1.ChatService.BroadcastMessage:input_type -> chat.v1.BroadcastRequest
	2, // 1: chat.v1.ChatService.GetOnlineUsers:input_type -> chat.v1.OnlineUsersRequest
	4, // 2: chat.v1.ChatService.NotifyPresence:input_type -> chat.v1.PresenceRequest
	1, // 3: chat.v1.ChatService.BroadcastMessage:output_type -> chat.v1.BroadcastResponse
	3, // 4: chat.v1.ChatService.GetOnlineUsers:output_type -> chat.v1.OnlineUsersResponse
	5, // 5: chat.v1.ChatService.NotifyPresence:output_type -> chat.v1.PresenceResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_v1_chat_proto_init() }
func file_api_proto_v1_chat_proto_init() {
	if File_api_proto_v1_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_v1_chat_proto_rawDesc), len(file_api_proto_v1_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_v1_chat_proto_goTypes,
		DependencyIndexes: file_api_proto_v1_chat_proto_depIdxs,
		MessageInfos:      file_api_proto_v1_chat_proto_msgTypes,
	}.Build()
	File_api_proto_v1_chat_proto = out.File
	file_api_proto_v1_chat_proto_goTypes = nil
	file_api_proto_v1_chat_proto_depIdxs = nil
}
